set(_CATKIN_CURRENT_PACKAGE "slam_gazebo")
set(slam_gazebo_VERSION "0.0.0")
set(slam_gazebo_MAINTAINER "rschmarci <rschmarci@todo.todo>")
set(slam_gazebo_PACKAGE_FORMAT "2")
set(slam_gazebo_BUILD_DEPENDS "roscpp" "rospy" "tf")
set(slam_gazebo_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "tf")
set(slam_gazebo_BUILDTOOL_DEPENDS "catkin")
set(slam_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(slam_gazebo_EXEC_DEPENDS "roscpp" "rospy" "tf")
set(slam_gazebo_RUN_DEPENDS "roscpp" "rospy" "tf")
set(slam_gazebo_TEST_DEPENDS )
set(slam_gazebo_DOC_DEPENDS )
set(slam_gazebo_URL_WEBSITE "")
set(slam_gazebo_URL_BUGTRACKER "")
set(slam_gazebo_URL_REPOSITORY "")
set(slam_gazebo_DEPRECATED "")